// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fstsnctvbuodwnhqucvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdHNuY3R2YnVvZHduaHF1Y3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjAzMjQsImV4cCI6MjA3MjQzNjMyNH0.dOBYQEpxBF2E5WT3giLzQGm8oxU19HabCKTLsUKk5zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});